name: mcserver_manager
description: Minecraft服务器管理工具
version: 1.4.0+7

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^11.0.0
  package_info_plus: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
